### ISSUE TITLE
ERA5/daily_surface_cancities_1990-1993.nc is missing `snd`

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim-testdata#12]
I think we may have accidentally removed this variable from the file. Causing errors with FWI test on Xclim.

**Comment by aulemahal** [comment]
Yes I realized that a bit too late...
However, it should be fixed in xclim's master, no?

The last fix PR was for the dimension order, but I didn't "fix" the snd name because the variable really is "swe" and snd can be _approximated_ from swe easily. If someone really wants "snd" in xclim's tests there is a new fixture `atmosds` that computes it by approximating a snow density of 300 kg/m³.

**Comment by Zeitsperre** [comment]
Yes, it is fixed. My master was a bit stale! Also, thanks for the explanation. Good to know!
